Added ability to un-select nav-buttons & rewrote nav-button SVG code …
DennisSSDev/Blazer pull request #3
Opened 2020-12-29 09:42 UTC by ncs2738

…to be more dry

2020-12-29 09:43 UTC, ncs2738 commented
Okiedokie, hopefully this worked!

2020-12-29 20:24 UTC, DennisSSDev requested changes
Pretty good for a first attempt! I have a few change requests but they are all simple to do

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +    if (isActive && unactiveEnum != undefined) {
you don't need to make a comparison to `undefined`. If you wrote it like this
```typescript
if(isActive && unactiveEnum){}
```
Typescript will assume that you want `unactiveEnum` to be valid (Truthy)

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +import { NavBarButtonGroupContext } from "vendrr/navbar/button-group-ctx";
We can't use the `vendrr` related packages inside `blazer-ui`. Anything within `blazer-ui` is supposed to be reusable across other projects we might want to do, thus anything inside `vendrr` is specific to the vendr app.

If you want to still make the `navbar button` generic anyways, it should exist within the `vendrr` subfolderer instead of `blazer-ui`

2020-12-29 20:24 UTC, DennisSSDev commented on src/vendrr/navbar/profile-button/index.tsx
> +  ProfileData.updateFunction = () => {
you shouldn't define the `updateFunction` within the `ProfileButton`. I think it should be defined together where you made the NavButtonData fields on line 16.

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  updateFunction?: any;
NIT: usually these types of functions are called `onUpdate` instead of `updateFunction`

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  activeEnum: number;
The actual type here is `ActiveNavBarButton`. `number` is technically correct, but it's hiding the actual type that we care about

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  unactiveEnum?: number;
Same here as the above comment regarding `number`

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  updateFunction?: any;
Also, the type can be this:
`() => void` which tells typescript that this variable will store a function that will return nothing

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  activeSVG: any;
the actual type here is this:
`(props: SVGProps<SVGSVGElement>) => JSX.Element`

2020-12-29 20:24 UTC, DennisSSDev commented on src/blazer-ui/core/navbar-button/index.tsx
> +  unactiveSVG?: any;
same as the comment above regarding svg

2020-12-30 01:12 UTC, DennisSSDev approved these changes
LGTM

2020-12-30 01:26 UTC, merged